<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<br>Verification failure: expected [abc] but found [xyz]<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Jun_11_23_32_24_AEST_2019.jpg><img src=Tue_Jun_11_23_32_24_AEST_2019.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Tests" duration-ms="26890" started-at="2019-06-11T13:32:24Z" finished-at="2019-06-11T13:32:51Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="6907" started-at="2019-06-11T13:32:24Z" finished-at="2019-06-11T13:32:31Z">
      <class name="com.XXX.TestCases.BankManagerLoginTest">
        <test-method status="PASS" signature="bankManagerLoginTest()[pri:0, instance:com.XXX.TestCases.BankManagerLoginTest@f2ff811]" name="bankManagerLoginTest" duration-ms="6650" started-at="2019-06-11T23:32:24Z" finished-at="2019-06-11T23:32:30Z">
          <reporter-output>
            <line>
              <![CDATA[<br>Verification failure: expected [abc] but found [xyz]<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Jun_11_23_32_24_AEST_2019.jpg><img src=Tue_Jun_11_23_32_24_AEST_2019.jpg height=200 width=200></img></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- bankManagerLoginTest -->
      </class> <!-- com.XXX.TestCases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="13793" started-at="2019-06-11T13:32:34Z" finished-at="2019-06-11T13:32:48Z">
      <class name="com.XXX.TestCases.AddCustomerTest">
        <test-method status="FAIL" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:com.XXX.TestCases.AddCustomerTest@1329eff]" name="addCustomerTest" duration-ms="13558" started-at="2019-06-11T23:32:34Z" data-provider="testData" finished-at="2019-06-11T23:32:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{postCode=5768, RunMode=Y, lastName=Arora, firstName=Raman, alertText=Customer added successfully with customer id}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at com.XXX.TestCases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="SKIP" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:com.XXX.TestCases.AddCustomerTest@1329eff]" name="addCustomerTest" duration-ms="4" started-at="2019-06-11T23:32:48Z" data-provider="testData" finished-at="2019-06-11T23:32:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{postCode=1234, RunMode=N, lastName=Tyagi, firstName=Rahul, alertText=Customer added successfully with customer id}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test case as the Run mode for data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test case as the Run mode for data set is NO
	at com.XXX.TestCases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
      </class> <!-- com.XXX.TestCases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
    <test name="Open Account Test" duration-ms="79" started-at="2019-06-11T13:32:50Z" finished-at="2019-06-11T13:32:51Z">
      <class name="com.XXX.TestCases.OpenAccountTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.XXX.TestCases.OpenAccountTest@5f683daf]" name="setup" is-config="true" duration-ms="9890" started-at="2019-06-11T23:32:14Z" finished-at="2019-06-11T23:32:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="openAccountTest(java.util.Hashtable)[pri:0, instance:com.XXX.TestCases.OpenAccountTest@5f683daf]" name="openAccountTest" duration-ms="6" started-at="2019-06-11T23:32:50Z" data-provider="testData" finished-at="2019-06-11T23:32:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{currency=Rupee, customer=Raman Arora}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test OPENACCOUNTTEST as the run mode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test OPENACCOUNTTEST as the run mode is set to NO
	at com.XXX.TestCases.OpenAccountTest.openAccountTest(OpenAccountTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAccountTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.XXX.TestCases.OpenAccountTest@5f683daf]" name="tearDown" is-config="true" duration-ms="356" started-at="2019-06-11T23:32:53Z" finished-at="2019-06-11T23:32:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.XXX.TestCases.OpenAccountTest -->
    </test> <!-- Open Account Test -->
  </suite> <!-- Data Driven Tests -->
</testng-results>
